name: Build & Package JavaFX App

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    name: Build on ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Grant execute permission to Gradle wrapper (Linux/macOS)
        if: runner.os != 'Windows'
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew clean jpackage

      - name: Upload package
        uses: actions/upload-artifact@v4
        with:
          name: DemoApp-${{ runner.os }}
          path: build/jpackage/
